---
title: "Plotting Diel 1"
author: "Angie Boysen"
date: "September 20, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(  
     message = FALSE,
     warning = FALSE,
     error = FALSE, 
     collapse = TRUE,
     comment = "#",
     fig.align = "center"
)

library(ggplot2)
library(gplots)
library(tidyr)
library(tibble)
require(graphics); require(grDevices)
library(Hmisc)
library(gtools)
library(cowplot)
require(RColorBrewer)
library(xlsx)
library(readr)
library(plotly)
library(stringr)
library(GGally)
library(ggbiplot)
library(stats)
library(dplyr)
```

##read in data
```{r}
dat.join.aq <- read_csv("Cyano_Aq_diel_1_Samples_Normalized_BlkSub_backfill_2IS_noblk.csv")
dat.join.aq <- dat.join.aq[,-1]
# dat.join.aq.less <- read_csv("Cyano_Aq_diel_1_Samples_Normalized_AllWays_noblk.csv")
```


##get sample data for non-IS cmpds
```{r echo=F}
samp.dat <- dat.join.aq %>% filter(type=="Smp") %>%
     filter(Compound.Name!="D-Tryptophan"&
                 Compound.Name!="D-Phenylalanine"&
                 Compound.Name!="d-IAA"&
                 Compound.Name!="d4-Tryptamine"&
                 Compound.Name!="Vitamin B2_IS"&
                 Compound.Name!="Vitamin B7_IS"& 
                 Compound.Name!="Vitamin B1_IS"&
                 Compound.Name!="D8-Arachidonic Acid") %>%
     select(Compound.Name,SampID,
            replicate, PooPlusModel,Notes) %>% 
     gather(Norm,RelArea,-Compound.Name,-SampID,-replicate, -Notes) %>%
     filter(replicate==1 | replicate==2 | replicate==3) %>%
     filter(!is.na(RelArea)) %>%
     mutate(SampID = as.numeric(SampID))
```

##More editing out of cmps that aren't good
```{r edit}
samp.dat <- samp.dat %>%
     filter(Compound.Name != "Indole 3 carboxylic acid" &
                 Compound.Name != "Kinetin" &
                 Compound.Name != "Pyridoxamine" &
                 Compound.Name != "Vitamin B9"  &
                 Compound.Name != "Vitamin C" &
                 Compound.Name != "thiamine pyrophosphate"&
                 Compound.Name != "Vitamin B1" &
                 Compound.Name != "Sulfurol")
```

##TIC
```{r TIC}
TIC <- samp.dat %>%
     group_by(SampID, replicate) %>%
     summarise(TIC = sum(RelArea))
```

##Plot TIC
```{r TICplot}
TIC.means <- TIC %>%
     group_by(SampID) %>%
     summarise(meanTIC = mean(TIC), sd = sd(TIC)) %>%
     mutate(lower = meanTIC - sd, upper = meanTIC + sd)

ggplot(TIC.means, aes(y= meanTIC, x = SampID)) + geom_point() + geom_line() + geom_ribbon(aes(ymin = TIC.means$lower, ymax= TIC.means$upper),alpha=0.1) + geom_vline(xintercept = c(5.5,11.5,17.5,23.5),linetype=2) 
```


##get sample means (not normalized by TIC)
```{r}
samp.dat.means <- samp.dat %>%
     select(-Norm, -Notes) %>%
     group_by(SampID, Compound.Name) %>%
     summarise(meanArea = mean(RelArea), sd = sd(RelArea))
```

##normalize to TIC)
```{r}
samp.TIC <- full_join(samp.dat, TIC) %>%
     mutate(Area.TIC = RelArea/TIC) %>%
     select(-Norm, -Notes, -TIC, -RelArea) %>%
     group_by(SampID, Compound.Name) %>%
     summarise(meanArea = mean(Area.TIC), sd = sd(Area.TIC)) %>%
     mutate(lower = meanArea - sd, upper = meanArea + sd)
```


##Get means and standard deviations, normalized to the max value
```{r echo=FALSE}
test.means <- samp.dat.means %>% select(-sd )%>% spread(Compound.Name, meanArea)

colMax <- function(data) sapply(data, max, na.rm = TRUE)
test.max <- colMax(test.means)

test.means.adjusted <- test.means
for(i in 2:length(test.max)){
     test.means.adjusted[,i] <- test.means[,i]/test.max[i]
}
Adjusted.Means.Long <- test.means.adjusted %>%
     gather(Compound.Name, AdjMean, -SampID)

test.sd <- samp.dat.means %>% select(-meanArea )%>% spread(Compound.Name, sd)
test.sd.adjusted <- test.sd
for(i in 2:length(test.max)){
     test.sd.adjusted[,i] <- test.sd[,i]/test.max[i]
}
Adjusted.SD.Long <- test.sd.adjusted %>%
     gather(Compound.Name, AdjSD, -SampID)

Adjusted.data <- full_join(Adjusted.Means.Long, Adjusted.SD.Long) %>%
     mutate(upper = AdjSD+AdjMean, lower = AdjMean-AdjSD)
```

##Add note/flag back in
```{r notes}
addNotes <- function(summarydata, notsumdata){
     samp.dat.means$Notes <- NA
     for (i in 1:nrow(samp.dat.means)){
          samp <- samp.dat.means$SampID[i]
          cmpd <- samp.dat.means$Compound.Name[i]
          Notes <- samp.dat %>%
               filter(Compound.Name==cmpd, SampID==samp) %>%
               select(Notes) 
          samp.dat.means$Notes[i] <- paste(Notes[[1]],collapse = " ")
     }
     samp.dat.means <- samp.dat.means %>%
          mutate(Flag = ifelse(test = grepl("BackFilled",
                                            Notes),
                               yes = "low",
                               no = ifelse(test = grepl("overloaded",
                                                        Notes),
                                           yes = "over",
                                           no = "ok")))
     Adjusted.data <- full_join(Adjusted.data, 
                                samp.dat.means[c("SampID", "Compound.Name",
                                                 "Flag")])
}
```


#line plots normed to max
```{r echo=FALSE}
p <- ggplot(Adjusted.data, aes(x=SampID, y=AdjMean)) + geom_point(aes(color = Flag)) + scale_color_manual(values = c("grey","black","red")) + geom_line() + facet_wrap(~Compound.Name, scales = "free")
p + geom_ribbon(aes(ymin = Adjusted.data$lower, ymax= Adjusted.data$upper),alpha=0.1) + geom_vline(xintercept = c(5.5,11.5,17.5,23.5),linetype=2) 
```

#line plots no norm to max
```{r echo=FALSE}
samp.dat.means <- samp.dat.means %>%
     mutate(upper = meanArea+sd, lower = meanArea-sd)

q <- ggplot(samp.dat.means, aes(x=SampID, y=meanArea)) + geom_point(aes(color = Flag)) + scale_color_manual(values = c("grey","black","red")) + geom_line() +   facet_wrap(~Compound.Name, scales = "free") 
q   + geom_vline(xintercept = c(5.5,11.5,17.5,23.5),linetype=2)
```


##SAH/SAM
```{r}
sah.sam <- Adjusted.data %>%
     filter(Compound.Name == "Adenosyl Homocysteine" |
                 Compound.Name == "Adenosyl Methionine") %>%
     select(SampID, Compound.Name, AdjMean) %>%
     spread(Compound.Name,AdjMean) %>%
     mutate(sah.sam = `Adenosyl Homocysteine`/`Adenosyl Methionine`)

ggplot(sah.sam, aes(x=SampID, y=sah.sam)) + geom_point() + geom_line() + geom_vline(xintercept = c(5.5,11.5,17.5,23.5),linetype=2) 

```


